PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golangci/golangci-lint
    tag: 'v1.23'

inputs:
- name: gpupgrade_src
  path: ../../../go/src/github.com/greenplum-db/gpupgrade

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    cd $GOPATH/src/github.com/greenplum-db/gpupgrade
    make lint
