PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.12.7'

inputs:
- name: gpupgrade_src
  path: ../../../go/src/github.com/greenplum-db/gpupgrade
- name: bats

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    export TERM=linux
    ./bats/install.sh /usr/local

    cd $GOPATH/src/github.com/greenplum-db/gpupgrade
    make depend
    make
    make check --keep-going
